spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/piko_admin
    username: piko_admin
    password: piko_admin
  mail:
    host: mailcatcher
    port: 1025
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092