spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/piko_locations
    username: piko_locations
    password: piko_locations
  cloud:
    stream:
      kafka:
        binder:
          brokers: kafka:9092